apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: map-display
  namespace: debezium-knative-demo
spec:
  template:
    spec:
      containers:
      - image: docker.io/gunnarmorling/debezium-knative-demo-temperature-map