apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source-enriched
  namespace: debezium-knative-demo
  labels:
    kafkasources.sources.knative.dev/key-type: int
spec:
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - temperature-values-enriched
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
