apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: map-events-trigger
  namespace: debezium-knative-demo
spec:
  broker: default
  # filter:
  #   attributes:
  #     type: dev.knative.kafka.event
  #     key: "7"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: map-display
