apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: map-events-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: map-display
